// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2a975945-b7d1-4086-9c87-3579656df1e9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_F4CMMpVPF",
    "aws_user_pools_web_client_id": "ajki95pfbofb4mgdqh9u742kn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cbjeh52qpva6to5xv4pys64cvq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
